#!/bin/sh

USER_DATA=/usr/data
PROG={moonraker_env}
TEMP_DIR={moonraker_dir}/tmp
HOME_DIR=/root
PY_SCRIPT={moonraker_dir}/moonraker/moonraker/moonraker.py
PRINTER_DATA_DIR=$USER_DATA/printer_data
PRINTER_CONFIG_DIR=$PRINTER_DATA_DIR/config
PRINTER_LOGS_DIR=$PRINTER_DATA_DIR/logs
PID_FILE=/var/run/moonraker.pid

start() {{
  [ -d $PRINTER_DATA_DIR ] || mkdir -p $PRINTER_DATA_DIR
  [ -d $PRINTER_CONFIG_DIR ] || mkdir -p $PRINTER_CONFIG_DIR
  [ -d $PRINTER_LOGS_DIR ] || mkdir -p $PRINTER_LOGS_DIR

  rm -rf $TEMP_DIR
  mkdir -p $TEMP_DIR

  TMPDIR=$TEMP_DIR HOME=$HOME_DIR start-stop-daemon -S -q -b -m -p $PID_FILE  --exec $PROG -- $PY_SCRIPT -d $PRINTER_CONFIG_DIR
}}
stop() {{
  start-stop-daemon -K -q -p $PID_FILE
}}
restart() {{
  stop
  sleep 1
  start
}}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {{start|stop|restart}}"
    exit 1
esac

exit $?
